courses/urls.py
from django.urls import path, include

from . import views


app_name='courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id>', views.show, name='show'),
    path('create/', views.create, name='create'),
    path('edit/<str:id>', views.edit, name='edit'),
    path('update/<str:id>', views.update, name='update'),
    path('delete/<str:id>', views.delete, name='delete')
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from web_project.routers import router
from django.conf import settings
from django.conf.urls.static import static

from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

   


urlpatterns = [
    path('', views.index, name='main'),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    path('courses/', include("courses.urls", namespace="courses")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/main/index.html
{% include "../header.html" %}
{% load static %}
{% url 'courses:index' as courses %}



<div class="wrap">
    <section class="info-block left">
        <div class="text-block">
            <h2 class="section-main">Учитесь там, где есть интернет</h2>
            <p class="text">Онлайн-школа с 1 по 11 класс для тех, кто не может посещать обычную школу. Учитесь, где удобно и когда удобно!</p>
        </div>
        
        <img src="{% static 'img/man-computer-book.png' %}"  alt="man-computer-book" class="medium-img">
    </section>
    <section class="info-block right">
        <img src="{% static 'img/man-screen-book.png' %}"  alt="man-computer-book" class="medium-img">
        <div  class="text-block">
            <h2 class="section-main">ОНЛАЙН-ШКОЛА</h2>
            <p class="text">Одна из ведущих онлайн-школ России, которая даёт полноценное обучение с 1 по 11 класс.
                 Все ученики, успешно сдавшие экзамены, получают аттестат государственного образца, который признается всеми ВУЗами России.
            </p>
        </div>
        
    </section>
    <a 
        class="to-lessons-btn btn btn-primary" 
        href="{{ courses }}"
    >
        Посмотреть курсы
    </a>
    
</div>

{% include "../footer.html" %}