courses/urls.py
from django.urls import path, include

from . import views


app_name='courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:id>', views.show, name='show'),
    path('create/', views.create, name='create'),
    path('edit/<str:id>', views.edit, name='edit'),
    path('update/<str:id>', views.update, name='update'),
    path('delete/<str:id>', views.delete, name='delete')
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from web_project.routers import router
from django.conf import settings
from django.conf.urls.static import static

from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

   


urlpatterns = [
    path('', views.index, name='main'),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    path('courses/', include("courses.urls", namespace="courses")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
from django.db import models
from simple_history.models import HistoricalRecords
# Create your models here.

class Course(models.Model):
    title = models.CharField(verbose_name='Course title ', max_length=255)
    description = models.TextField(verbose_name='Course description')
    cost = models.IntegerField(verbose_name='Course price ', default=1)
    duration = models.IntegerField(verbose_name='Course duration in month ', default=1)

    history = HistoricalRecords()
    
    def __str__(self):
        return self.title
    
    
    class Meta:
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'

courses/forms.py
from django.forms import fields
from courses.models import Course
from django import forms

from django.utils.translation import gettext_lazy as _


class CourseForm(forms.ModelForm):
    
    class Meta:
        model = Course
        fields = "__all__"
        
        labels = {
            'title': _('Название'),
            'description': _('Описание'),
            'cost': _('Цена'),
            'duration': _('Продолжительность'),
        }

courses/views.py
from courses.models import Course
from comments.models import Comment

from courses.serializers import CourseSerializer
from django.shortcuts import render, redirect
from rest_framework.viewsets import ModelViewSet
from django.db.models import Q

from courses.forms import CourseForm


class CourseViewSet(ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    
def index(request):
    search_query = request.GET.get('search')
    select = request.GET.get('select')
    
    if search_query:
        try:
            courses = Course.objects.filter(Q(title__contains=search_query) | Q(description__contains=search_query))
        except:
            courses = None
    else:
        courses = Course.objects.all()

    if select:
        try:
            courses = courses.order_by(select)
        except:
            print('Хуйня', select)
    
    
    form = CourseForm()
    context = {'courses': courses, 'form': form, 'search': search_query}
    return render(request, 'courses/index.html', context)

def show(request, id):
    course = Course.objects.get(pk=id)
    reviews = Comment.objects.filter(course_id_id=id)
    context = {'course': course, 'reviews': reviews}
    
    return render(request, 'courses/show.html', context)

def create(request):
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("courses:index")
            except Exception as e:
                print(e)
    else:
        form = CourseForm()
    
    courses = Course.objects.all()
    return render(request, 'courses/index.html', { 'form': form, 'courses': courses })
    
def edit(request, id):
    course = Course.objects.get(id=id)
    form = CourseForm
    return render(request, 'courses/edit.html', { 'course': course, 'form': form  })

def update(request, id):
    course = Course.objects.get(id=id)
    form = CourseForm(request.POST, instance=course)
    if form.is_valid():
        form.save()
        return redirect("courses:show", id=id)
    
    return render(request, 'courses/edit.html', { 'course': course, 'form': form })

def delete(request, id):
    course = Course.objects.get(id=id)
    course.delete()
    return redirect('/courses')



            

courses/templates/courses/edit.html
{% load static %}
{% load getattribute %}


{% include "../header.html" %}

<div  class="create-new">
    <div  class="new-item-form">

        <form method="POST" action="{% url 'courses:update' id=course.id %}" id="new-lesson-form"  class="join-form">
            {% csrf_token %}
            {% if form %}
                {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.errors|escape }}</strong>
                        </div>
                        {% endif %}
                        <div class="form-group">
                
                            <label for="{{ field.name }}">{{ field.label }} курса</label>
                            <input  type="text" class="form-control" name="{{ field.name }}" id="{{ field.name }}"  value="{{ course|getattribute:field.name }}">
                        </div>
                {% endfor %}

            {% endif %}

            <button  onclick="closeNewLessonForm()" type="submit" class="form-btn btn btn-primary">Подтвердить</button>
        </form>
    </div>
</div>


{% include "../footer.html" %}

courses/templates/courses/index.html
{% load static %}
{% include "../header.html" %}


    <div class="order-form-container">
        <form method="GET" action="{% url 'courses:index' %}">
            <button class="order-form__btn">
                Подтвердить
            </button>
            <input style="display: none;" name="search" value="{{ search }}">
            <select name="select">
                <!--Supplement an id here instead of using 'name'-->
                <option value="title" selected>название</option>
                <option value="cost">Цена по возрастанию</option>
                <option value="-cost">Цена по убыванию</option>
            </select>
        </form>
    </div>
    

    {% include "./new_lesson_menu.html" %}


    <div class="items-container ">
        {% if courses %}
            {% for course in courses %}
            <div class="lesson">
                <a 
                    class="link" 
                    href="/courses/{{ course.id }}"
                >
                    <img src="{% static 'img/man-computer-book.png' %}" alt="lesson-preview" class="lesson__img">
                    <div class="lesson__text-block">
                        <h3 class="lesson__name">{{ course.title }}</h3>
                        <p class="lesson__description">{{ course.description|truncatewords:15 }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        {% else %}
            <h3 style="text-align: center; margin-bottom: 80px;">
                 Нет совподающих результатов
            </h3>

        {% endif %}
    </div>




{% include "../footer.html" %}

courses/templates/courses/new_lesson_menu.html
<button  class="form-btn btn btn-secondary" id="open-form" onclick="openNewLessonForm()">Создать новый курс</button>
<div  class="create-new" style="display: none;">
    <div  class="new-item-form">
        <button onclick="closeNewLessonForm()" class="close-menu-btn no-style-btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 32 32">
                <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
            </svg>
        </button>
        <form method="POST" action="{% url 'courses:create' %}" id="new-lesson-form"  class="join-form">
            {% csrf_token %}
            {% if form %}
                {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.errors|escape }}</strong>
                        </div>
                        {% endif %}
                        <div class="form-group">
                
                            <label for="{{ field.name }}">{{ field.label }} курса</label>
                            <input  type="text" class="form-control" name="{{ field.name }}" id="{{ field.name }}"  placeholder="Enter {{ field.name }}">
                        </div>
                {% endfor %}

            {% endif %}

            <button  onclick="closeNewLessonForm()" type="submit" class="form-btn btn btn-primary">Подтвердить</button>
        </form>
    </div>
</div>

courses/templates/courses/show.html
{% load static %}
{% include "../header.html" %}



<div class="lesson-show">

    <div class="setting-menu-container">
        <button onclick="ToggleSettingMenu()" class="setting-btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
                <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
                <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
            </svg>
        </button>
        <div class="setting-menu">
            <a class="setting-menu-item" href="/courses/delete/{{ course.id }}">Удалить</a>
            <a class="setting-menu-item" href="/courses/edit/{{ course.id }}">Редактировать</a>
        </div>
    </div>

    <h2  class="lesson-show__name">
        {{ course.title }}
    </h2>
    <div class="lesson-show__params">
        <p class="lesson-show__params__cost lesson-show__params-param">Цена: <span class="value">{{ course.cost }}</span> р.</p>
        <p class="lesson-show__params__duration lesson-show__params-param">Продолжительность: <span class="value">{{ course.duration }} </span>мес.</p>
    </div>
    <div class="lesson-show__description">
        <p class="lesson-show__description__text">{{ course.description }}</p>
    
        <img src="{% static 'img/man-computer-book.png' %}" class="medium-img" alt="">
    </div>
    <button onclick="openModalWindow()" class="join btn btn-primary">Записаться</button>
    
    
    
    <div class="reviews">
        <h3 class="reviews__title">Отзывы</h3>
        <button onclick="openReviewForm()" type="button" class="btn btn-secondary send-review">Оставить озыв</button>
        <div  class="reviews__new-review-form" style="display: none;">
            <form class="join-form">
                <div class="inp">
                    <p  class="inp__description">Текст отзыва: <button  onclick="closeReviewForm()" class=" btn btn-light close">Close</button></p>
                    <input type="text" class="inp__text" placeholder="Введите текст" name="name"  required >
                </div>
    
                <button  onclick="checkReviewForm()"  class="review-submit-btn btn btn-primary">Оставить отзыв</button>
            </form>
        </div>
        <div class="reviews__container">
            {% for review in reviews %}
                <div class="review">
                    <img src="{% static 'img/man.jpg' %}" class="review-character">
                    <p class="review-text">{{ review.text }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
    
</div>

{% include "../footer.html" %}